name: Setup Java and Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: setup-maven@v1
        with:
          maven-version: '3.9.6' # Specify the desired Maven version

      - name: Verify Maven version
        run: mvn --version
