name: Build with JDK 17 and latest Maven

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Remove existing Maven
        run: sudo apt-get remove -y maven

      - name: Install latest Maven
        run: |
          MAVEN_VERSION=3.9.4
          wget https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar xzvf apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
          sudo ln -s /opt/maven/bin/mvn /usr/bin/mvn

      - run: mvn --version
